### ISSUE TITLE
отображение кластерпрофайла 

### ISSUE THREAD

**Issue by seamen01** [sbprov2/SBProV2#174]
чуть ниже уже был подобный вопрос, но немного хочу конкретизировать его. Кластер профайл отображается в СБ2 намного хуже, чем в СБ1. 
сравнение СБ1 и СБ2 показал на рисунке, Если возможно добиться такой настройки в СБ2, то пожалуйста покажите как это сделать
http://prntscr.com/bmmfy1

**Comment by yamaha72** [comment]
Всё переделали как в первой версии. Для дополн. настроек поиграйтесь c ChartSettings -> Auto Profile Rating и Cluster Profile Rating.

Если стоит галочка Auto Profile Rating и Cluster Profile Rating = 0 то ширина всех кластеров выстраивается от мах объема среди всех кластеров на графике.

Если стоит галочка Auto Profile Rating и Cluster Profile Rating > 0 то ширина всех кластеров выстраивается от того что указано в поле Cluster Profile Rating.

Если галочки в Auto Profile Rating нету, то ширина кластеров в каждом баре выстраивается от мах объёма в своём баре.

Изменения будут доступны после следующего обновления
