### ISSUE TITLE
Не видно баров на кластерном графике

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#187]
На кластерном графике не видны бары вверх. Вниз красного цвета видны (но плохо), а вверх пробовал и синий и зеленый - не видно все равно.
Надо либо сделать их толще, либо дать пользователю возможность самому изменять толщину.
![sb-pro-v2 6](https://cloud.githubusercontent.com/assets/19690193/16512483/87a66fc2-3f64-11e6-9ab8-1cd08ae1d232.jpg)

**Comment by net02worm** [comment]
Да, есть такое, я тоже замечал это.

**Comment by Igor731** [comment]
И еще. Сейчас от лоу до хай проведена вертикальная тонкая белая линия. Она не нужна. Только мешает. Если кому нужна, то пусть ставит Third Volume = 0 B И тогда пусть помечаются даже нулевые объемы. Иначе - только отфильтрованные.

**Comment by Igor731** [comment]
И еще. Повторю, что уже было написано. Слишком рано при сжатии по цене кластерного графика начинают сливаться линии объемов. В старой версии это сделано оптимально. Надо и здесь так сделать.

**Comment by sbprov2** [comment]
Может стоит поставить более яркий цвет, чтобы было лучше видно направление бара?
Даже на вашем скриноте, у вас стоит темной синий цвет - понятно, что это будет плохо видно на черном фоне.

**Comment by Igor731** [comment]
В том то и дело, что всякие перепробовал - не видно. Надо менять толщину. Лучше, если можно будет настраивать.
А два предыдущих пожелания прокомментируйте, пожалуйста.  Хотелось бы, чтобы были учтены.

**Comment by Igor731** [comment]
По поводу невидимости бара. Если поставить яркий цвет, его видно будет, но тогда ценовая метка не читаема, так как у нее тот же цвет, что и у бара.
