### ISSUE TITLE
Ошибка сохранения профиля (ageev.s@gmail.com)

### ISSUE THREAD

**Issue by test-777** [sbprov2/SBProV2#188]
Сохранив профиль с таймфреймом 15 минут при его загрузке тафмрейм выставляется на 5 минутку. Глюк появился в последнем обновлении  (28.06.2016) -  поправьте пожалуйста ато приходиться каждый раз переключать на нужный тайм.

**Comment by sbprov2** [comment]
Знаем, будет исправлено в следующем обновлении.
