### ISSUE TITLE
Cluster Chart - нужна реализация точно, как в V1 (ermak13@gmail.com)

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#192]
Вот так реализовано в V1. Растянутый график:
![sb-pro-v2 7](https://cloud.githubusercontent.com/assets/19690193/16540497/b121f8ec-406f-11e6-9825-f7c3da10d4c0.jpg)
Сделано четыре цвета. 1)темно-серый (не изменяемый) - объемы, не удовлетворяющие ни одному из условий фильтров, а также меньшие какой-то величины X, заданной разработчиком. 2)светло-серый (не изменяемый) - объемы (аналог фильтра Third Volume), большие X, но меньшие Second Volume. 3)желтый - объемы Second Volume фильтра (устанавливаемый). 4) красный - макс объем (устанавливаемый).
Нужно сделать именно так. Можно только Third Volume оставить устанавливаемым, но исправить его работу, но лучше даже и без него. Если на каких-то ценовых уровнях вообще не было сделок, то оставлять их пустыми. Никакой вертикальной линии от лоу до хай нет и не должно быть.

Сильно сжатый график:
![sb-pro-v2 8](https://cloud.githubusercontent.com/assets/19690193/16540500/c79c4a82-406f-11e6-9cf3-39519c2ca88a.jpg)
Даже при сильном сжатии линии так и не слились. В процессе сжатия они утончаются до тех пор, пока это технически возможно (может даже до пикселя). И только потом из двух линий делается одна и так дальше.
В V2 они сливаются очень быстро, что визуально намного хуже.

**Comment by yamaha72** [comment]
Всё переделали как в первой версии. Для дополн. настроек поиграйтесь c ChartSettings -> Auto Profile Rating и Cluster Profile Rating.

Если стоит галочка Auto Profile Rating и  Cluster Profile Rating = 0 то ширина всех кластеров выстраивается от мах объема среди всех кластеров на графике.

Если стоит галочка Auto Profile Rating и  Cluster Profile Rating > 0 то ширина всех кластеров выстраивается от того что указано в поле Cluster Profile Rating.

Если галочки в Auto Profile Rating нету, то ширина кластеров в каждом баре выстраивается от мах объёма в своём баре.

Изменения будут доступны после следующего обновления

**Comment by Igor731** [comment]
Я совсем о другом говорил.

**Comment by Igor731** [comment]
Существенно лучше. Но еще не так, как в V1.

"Сделано четыре цвета. 1)темно-серый (не изменяемый) - объемы, не удовлетворяющие ни одному из условий фильтров, а также меньшие какой-то величины X, заданной разработчиком. 2)светло-серый (не изменяемый) - объемы (аналог фильтра Third Volume), большие X, но меньшие Second Volume. 3)желтый - объемы Second Volume фильтра (устанавливаемый). 4) красный - макс объем (устанавливаемый).
Нужно сделать именно так. Можно только Third Volume оставить устанавливаемым, но исправить его работу, но лучше даже и без него. Если на каких-то ценовых уровнях вообще не было сделок, то оставлять их пустыми."

**Comment by Igor731** [comment]
Да, и Third Volume теперь работает.
