### ISSUE TITLE
Тормозит Рос.рынок(avkzn@yandex.ru)

### ISSUE THREAD

**Issue by avkzn** [sbprov2/SBProV2#195]
Друзья, а у кого-нибудь еще тормозит получение онлайн данных с Российского рынка?
С 30 июня как это началось и до сих пор нет стабильной работы.
По нефти на ФОРТСе сегодня вообще не идут данные.

**Comment by sbprov2** [comment]
Нефть уже должна работать, насчет тормозов - у нас их точно нет (сравнивали с Quik).
В конце июля, после испрвления всех багов - будут коннекторы, и сможете себе подключить данные, если хотите чтобы задержки не было вообще никакой.

**Comment by avkzn** [comment]
Спасибо!
