### ISSUE TITLE
Cluster Chart пока не совсем так, как в V1

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#206]
Слишком рано при сжатии начинают сливаться объемы.
Должно быть при соответствующем сжатии так:

![sb-pro-v2 7](https://cloud.githubusercontent.com/assets/19690193/16586440/9d38699a-42ce-11e6-8d91-b700089cdec7.jpg)

А у вас так:

![sb-pro-v2 8](https://cloud.githubusercontent.com/assets/19690193/16586424/82465138-42ce-11e6-8c36-93be80ff9790.jpg)

**Comment by aj77777** [comment]
Обновите, cluster profile просто офигенный получился , спасибо РАЗРАБОТЧИКАМ !!!

**Comment by Igor731** [comment]
Так это новый наверху от 05.07

**Comment by Igor731** [comment]
Еще все-таки лучше было бы самим устанавливать цвет объемов, не удовлетворяющих фильтру Third Volume.

**Comment by aj77777** [comment]
НАВЕРХУ ПЕРВАЯ ВЕРСИЯ ПОВНИМАТЕЛЬНЕЙ!

**Comment by sbprov2** [comment]
При большом сжатии не получится сделать что-бы не сливалось. Минимальная единица измерения 1 пиксель. В первой версии тоже сливается, если сильно сжать. В v2 другая система отрисовки, сделали все что могли, дальше уже некуда.

**Comment by Igor731** [comment]
Как же в V1 сделано?

**Comment by Igor731** [comment]
Про сжатие понял, а с этим как?
"Все-таки лучше было бы самим устанавливать цвет объемов, не удовлетворяющих фильтру Third Volume. Чуть посветлее они должны быть, как в V1."

**Comment by sbprov2** [comment]
Там есть ClusterProfile background

**Comment by seamen01** [comment]
тоже согласен, что не совсем так сделано как в первой версии. пришлось третьим фильтром добиваться более менее соответствия, но все равно еще не то
