### ISSUE TITLE
Ошибка в Clouds

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#208]
До апплай:

![sb-pro-v2 10](https://cloud.githubusercontent.com/assets/19690193/16594055/25117236-42f1-11e6-83f6-5b308b5227e6.jpg)
После:
![sb-pro-v2 11](https://cloud.githubusercontent.com/assets/19690193/16594063/30246598-42f1-11e6-9121-0ac74b1e5c4a.jpg)

Это часы. На днях то же самое.

**Comment by sbprov2** [comment]
Уже знаем, проблема требует времени. Будем исследовать.

**Comment by Igor731** [comment]
Возможно ли хотя бы сказать, какой вариант правильный. Когда по истории цепочки строятся или в реал тайме?

**Comment by sbprov2** [comment]
Эта проблема исправлена
