### ISSUE TITLE
Мануал cloud (avkzn@yandex.ru)

### ISSUE THREAD

**Issue by avkzn** [sbprov2/SBProV2#211]
Добрый день!
Скажите пож-та, а когда планируется выпуск мануала по Cloud?
Понимаю, что 90% информации можно взять из видео версии 1 на сайте, но как мне кажется во второй версии отличия все-таки есть.
Пока что успел увидеть, в режиме Single mode(Trades), во второй версии не нашел где в меню  Cloud Setting указывается First limit and Second limit.
Спасибо!

**Comment by sbprov2** [comment]
Добрый день, мануал будет в ближайшие 1-2 недели.

**Comment by avkzn** [comment]
Спасибо!
