### ISSUE TITLE
Buy = ask?..

### ISSUE THREAD

**Issue by makarovas** [sbprov2/SBProV2#212]
Раньше в программе было указано Bid (Sell), Ask (Buy), теперь просто sell - buy(в частности в Cloud algo), а так ли это..Прошу изменить формулировки в программе на дефолт с sell - buy на bid - ask.
Маркетные ордера это хорошо спору нет, но есть еще и лимиты, зачем так ущемлять их права)?
(makarofalex@gmail.com)

**Comment by sbprov2** [comment]
Укажите пожалуйста точно, где и что нужно изменить во всей платформе.

**Comment by makarovas** [comment]
![2016-03-29_180857](https://cloud.githubusercontent.com/assets/3993670/16618356/a733a2f2-4391-11e6-9dd1-c0309d4197b0.jpg)

**Comment by makarovas** [comment]
![2](https://cloud.githubusercontent.com/assets/3993670/16618465/32835d2a-4392-11e6-936b-0b7e1f8f0b90.jpg)

**Comment by icesoye** [comment]
> Раньше в программе было указано Bid (Sell), Ask (Buy),

С V1 там стоит Buy и Sell. Какой смысл это менять?

**Comment by makarovas** [comment]
Смысл такой: Buy, Sell это торговые рекомендации основанныега том, что в моменте точно проходили маркетные ордера (на вход). Но это может быть вход лимитом, вход маркетом, выход лимитом, выход маркетом, те 1/4 от истины. Маркировка Bid / Ask это на 100% объективно, дальше необходимо опираться на свою логику.

**Comment by makarovas** [comment]
Спасибо большое за учтенное предложение, можно только в самом тэге поменять местами значения: ASK - BID, на BID - ASK
![3](https://cloud.githubusercontent.com/assets/3993670/16707490/8ae64b10-45d8-11e6-93e0-dbe85e759e07.jpg)
