### ISSUE TITLE
Cloud/Rating/Detection (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#216]
Включаем фильтр Cloud
http://prntscr.com/bpjxck
Ставим галочку Bid/Ask
http://prntscr.com/bpjxjh
За возможность делать все на "лету" спасибо - очень помогает.
Ставим Detection на фильтр - Apply (на этом месте настройки на "лету" перестают быть на "лету" - вводим цифпы)
http://prntscr.com/bpjy27
Убираем Bid/Ask
http://prntscr.com/bpk55d - Apply
Убираем Detection - Apply
http://prntscr.com/bpk69j

1. Все круги стали одинаковыми - это недочет (автоматически поменялся Rating)
2. Можно ли сделать так чтобы Rating был всегда одинаковым и не менялся вообще, ни прикаких настройках? (или галочку добавить чтобы отключать автоматическое его изменение)
3. Зачем вообще меняется Rating если фильтр один, а Bid/Ask фильтр только окрашивает круги (что он и должен делать в принципе) - это фактически тот же фильтр Cloud только с окрашенными кругами, так зачем эти сложности все?
Если можно сделайте это для всех фильтров типа bid/ask, где это возможно.

upd. 
1. Да и настройки Rating, галочка bid/ask не сохраняются - не сохраняются в профиле.
2. Rating сбрасывается при изменении ТФ с включенным bid/ask.

**Comment by Igor731** [comment]
А Detection что такое? Забыл. Не пользовался никогда.

**Comment by Igor731** [comment]
Неплохо было бы еще параметр в Clouds добавить. Min Difference. И рисовать круги только для Difference >= Min Difference.

**Comment by icesoye** [comment]
>А Detection что такое? Забыл. Не пользовался никогда.

А вот я ВСЕ обучающие видео с сайта посмотрел :) Определяет если в цепочке лот равный или больший, чем фильтр.

**Comment by Igor731** [comment]
Спасибо. Я тоже смотрел. Давно уже. Не пользовался - вот и забыл.
Наверно, "Определяет есть ли в цепочке лот"

**Comment by icesoye** [comment]
>Неплохо было бы еще параметр в Clouds добавить. Min Difference. И рисовать круги только для Difference >= Min Difference.

Что такое Difference?

**Comment by Igor731** [comment]
![sb-pro-v2 15](https://cloud.githubusercontent.com/assets/19690193/16632135/5a3f2f2c-43cb-11e6-9624-baa20e17f64b.jpg)

**Comment by Igor731** [comment]
То, что Detection так меняет (делает одинаковым) размер клоудс, это конечно ошибка.

**Comment by icesoye** [comment]
>То, что Detection так меняет (делает одинаковым) размер клоудс, это конечно ошибка.

Сам Detection не меняет, меняет Rating - он автоматически меняет значение на 80 (хотя стояло и 200 до этого, к примеру) при установке галочки Bid/Ask. А автоматически менять не должен - это вводит в замешательство.

**Comment by Igor731** [comment]
Хорошо было бы как-то еще сделать, чтобы при установленном Bid/Ask Difference было еще и визуально понятно, в какой цепочке больше лотов. Как вариант, чем больше лотов, тем толще линия окружности.

**Comment by Igor731** [comment]
Я это и имел ввиду. Изменение Детекшин не должно менять рейтинг. Его вообще должно быть можно только вручную устанавливать.

**Comment by icesoye** [comment]
>Хорошо было бы как-то еще сделать, чтобы при установленном Bid/Ask Difference было еще и визуально понятно, в какой цепочке больше лотов. Как вариант, чем больше лотов, тем толще линия окружности.

http://prntscr.com/bpno61 - Ну вот визуально (рисовал как мог :D ) все что попадает в Detection - зеленое, ниже серое. Потому что главное не "больше лотов" - что отсеивается по Rating -  а какими лотами входили, а то может просто ритейл снесли (тогда будет 1 -3 лота в цепочке), или кто-то кинул лот большой (>= 10 лотов ну и по айсбергам смотреть уже нужно)

**Comment by Igor731** [comment]
Я понял. Согласен.

**Comment by Igor731** [comment]
Тогда напрашивается режим, в котором при установленном Detection Rating прямо пропорционален размеру самого крупного тика в цепочке.

**Comment by Igor731** [comment]
А ведь сейчас как раз именно так и сделано.

**Comment by sbprov2** [comment]
Можно ли сделать так чтобы Rating был всегда одинаковым и не менялся вообще, ни прикаких настройках? (или галочку добавить чтобы отключать автоматическое его изменение)

----> нет, нельзя. Rating автоматически подстраивается под Summ. Limit. Если не изменяет его автоматически, на графике будет кошмар. **ЭТО ИСКЛЮЧЕНО!**

**Comment by sbprov2** [comment]
Включаем фильтр Cloud
http://prntscr.com/bpjxck
Ставим галочку Bid/Ask
http://prntscr.com/bpjxjh
За возможность делать все на "лету" спасибо - очень помогает.
Ставим Detection на фильтр - Apply (на этом месте настройки на "лету" перестают быть на "лету" - вводим цифпы)
http://prntscr.com/bpjy27
Убираем Bid/Ask
http://prntscr.com/bpk55d - Apply
Убираем Detection - Apply
http://prntscr.com/bpk69j

Все правильно алгоритм работает. Где там что одинаковое не понятно. Все вернулось в первоначальный вид, как на первом скриншоте - так и должно быть. Никаких ошибок тут нет. Вы отключили bid-ask и убрали Detection.

**Comment by sbprov2** [comment]
Rating сбрасывается при изменении ТФ с включенным bid/ask.
-> Такой ошибки тоже не наблюдаем.

**Comment by icesoye** [comment]
>Все правильно алгоритм работает. Где там что одинаковое не понятно. Все вернулось в первоначальный вид, как на первом скриншоте - так и должно быть. Никаких ошибок тут нет. Вы отключили bid-ask и убрали Detection.
ну если это нормально, значит вопрос закрыт.
просто хотелось бы видеть картину такой
http://prntscr.com/bpxmv5
а не каждый раз настраивать.

**Comment by icesoye** [comment]
вы не так поняли наверное - 
я просто предложил чтобы разница между этим
http://prntscr.com/bpxmv5
и этим
http://prntscr.com/bpxqkc
Была в галочке bid/ask (без изменения рейтинга на число меньшее чем сейчас)
При установке данной галочки график из первого преобразовывается вот в такое (рейтинг меняется с 200 на 80 - и на графике просто каша)
http://prntscr.com/bpxsk4

Ну где тут кошмар то? :( Можно сделать хотя бы чтобы рейтинг не менялся на значение меньшее чем стоит сейчас.
Ладно, вам виднее, закрыли так закрыли.

**Comment by yamaha72** [comment]
icesoye "Зачем вообще меняется Rating если фильтр один, а Bid/Ask фильтр только окрашивает круги"

при Bid/Ask диаметр круга зависит от его Difference. Поэтому когда ставите галочку Bid/Ask изменяется Rating = 80. Круг, у кот Difference = 80 рисуется с диаметром 50 пикселей, все остальные круги рисуются с диаметром в зависимости от своего Difference, но не мение 10  пикселей

**Comment by Igor731** [comment]
Тогда напрашивается режим, в котором при установленном Detection, размер круга прямо пропорционален размеру самого крупного тика в цепочке. Если же он равен 0, то прямо пропорционален величине Bid/Ask Difference. Можно это сделать?

**Comment by yamaha72** [comment]
Я так понимаю, в вашем случае все круги имели одинаковый Difference = 100%, поэтому все они имели одинаковый диаметр

Ошибку сохранения в профиле BidAsk исправлена, а Rating вродь и так сохранялся и при изменении таймфрейма не сбрасывается. Если у вас не так - пишите

**Comment by icesoye** [comment]
>при Bid/Ask диаметр круга зависит от его Difference. Поэтому когда ставите галочку Bid/Ask изменяется Rating = 80. Круг, у кот Difference = 80 рисуется с диаметром 50 пикселей, все остальные круги рисуются с диаметром в зависимости от своего Difference, но не мение 10  пикселей

у меня фильтр клауд на котором - все и всегда 100% diff (очень маленький range) - даже в цепочку смотреть не надо, там минимум будет 90%-95%. - и на графике все круги одинаковые, то что от Diff зависит это не очень хорошо - для таких фильтров как у меня. Ладно, идею понял.

**Comment by RichAndHappy** [comment]
1 - http://shot.qip.ru/00zDYs-5MQ9Hq5VJ/
2 - http://shot.qip.ru/00zDYs-1MQ9Hq5VK/
применил настройки (Apply)
3 - http://shot.qip.ru/00zDYs-1MQ9Hq5VM/
Я так понял нужен 2 случай применения.

**Comment by icesoye** [comment]
в общем я понял что данная картинка при diff = 100% Неосуществима, все всех благодарю, буду и дальше юзать костыли )
http://prntscr.com/bpych9

**Comment by Igor731** [comment]
Так и не понял, что ты хочешь. Чтобы при diff=100% размер круга был бы не одинаковым? А пропорционален чему, Detection?

**Comment by icesoye** [comment]
>Так и не понял, что ты хочешь. Чтобы при diff=100% размер круга был бы не одинаковым? А пропорционален чему, Detection?

пропорционален обьему - необходимо для того чтобы видеть где "толкают" рынок, где выносят стопы, кто преобладает на рынке - покупатель или продавец и т.п. А difference такого конечно же не покажет - он покажет общий обьем.
Такое difference не покажет. Потому что он всегда 100% )))
Вот для примера - размер круга от обьема. Ренж очень мелкий, ну фильтр я вроде кидал.
Лонгисты
http://prntscr.com/bpyuz2
http://prntscr.com/bpyuo7
Слом тренда
http://prntscr.com/bpyv40
Шортисты
http://prntscr.com/bpyus7
