### ISSUE TITLE
Bid/Ask Difference не сохраняется. 

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#219]
После загрузки галочки нет. Получается вот что.
![sb-pro-v2 14](https://cloud.githubusercontent.com/assets/19690193/16631418/b8aa5d10-43c7-11e6-9161-c93819c39741.jpg)

**Comment by icesoye** [comment]
Вот тут описал - https://github.com/sbprov2/SBProV2/issues/216

**Comment by test-777** [comment]
подтверждаю в настройках галочка снимается после загрузки.
