### ISSUE TITLE
CLOUD algo - double click active view (просмотр содержимого Cloud)

### ISSUE THREAD

**Issue by makarovas** [sbprov2/SBProV2#221]
1. CLOUD algo - double click active view
Прошу вернуть one click view для просмотра содержимого Cloud. Double click постоянно щелкать очень не удобно.
![image](https://cloud.githubusercontent.com/assets/3993670/16644120/14aa85b2-4423-11e6-8cfd-e6b2fa005f59.png)
2. Прошу добавить функцию "активного просмотра CLOUD algo".
Т.е. при возникновении новых Clouds удовлетворяющих условию поиска, содержимое отображается автоматически на графике, без дополнительных кликов.

(makarofalex@gmail.com)

**Comment by sbprov2** [comment]
Мои доводы против:

1. А если вы мышкой при передвижении графика будете попадать на cloud - то будет выскакивать информация. Довольно часть такое можно быть, что не удобно. Дабл клик вполне адекватный вариант, вы же в windows папки открываете дабл кликом, и никто не жалуется.

2. Если будет вылезать большое кол-во эллипсов, весь экран будет усеян информацией. Кроме того, нажать два раза на круг не тяжело (не вижу в этом большой проблемы)


Чтобы это предложение стало задачей, ее должны поддержать пользователи. Добавил label коллективное обсуждение.

**Comment by icesoye** [comment]
@sbprov2 +1 функциональной полезности изменение с double click - one click не несет вообще, просто потому что неудобно. Тут еще пилить и пилить этот клиент и просто недобно два раза мышкой щелкнуть это самое меньшее из бед.
