### ISSUE TITLE
+  в режиме CLOUD ошибки (zhivits@gmail.com)

### ISSUE THREAD

**Issue by zhivik007** [sbprov2/SBProV2#223]
http://savepic.net/8241911.htm
по одной цене разные показатели, хотя настройки стандартные...

**Comment by icesoye** [comment]
у вас считает в рэнже 10 тиков - так что такое вполне может быть, поставьте ренж 1 тик и посмотрите еще раз.

**Comment by Igor731** [comment]
А ренж разве не в пипсах? Тик это ведь одна сделка, а пипс это минимальный шаг цены.

**Comment by icesoye** [comment]
Тик, пипс - да не правильно выразился, поставьте вот это Range (pips) значение - 1-3

**Comment by sbprov2** [comment]
Вы сравниваете кластер c Cloud? Это же разные алгоритмы, абсолютно, значения и не должны совпадать.

**Comment by zhivik007** [comment]
...я ничего не сравниваю!!!!, вопрос - почему  Cloud по одной цене(!!!!) дает два варианта !!!. при единственном  Cloud на графике, и со стандартными настройками...???
