### ISSUE TITLE
Серебро минуты. На увеличившейся волатильности - пропущены 15 мин данных

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#228]
![sb-pro-v2 16](https://cloud.githubusercontent.com/assets/19690193/16687370/de4ddea2-4520-11e6-9bf6-614ae688f530.jpg)
После апплай - данные считались. Наверно это мой не быстрый мобильный интернет 4G

**Comment by sbprov2** [comment]
В это время мы перезагружали сервер вероятно.
