### ISSUE TITLE
+  в режиме CLOUD ошибки(2) (zhivits@gmail.com)

### ISSUE THREAD

**Issue by zhivik007** [sbprov2/SBProV2#230]
повторяю вопрос...:
-как клауд может считать по одной цене дважды...???
(крокодил одной длины ...как его не меряй!!!)
http://savepic.net/8234539.htm

вариант1: http://savepic.net/8238634.htm
вариант2: http://savepic.net/8225322.htm
это на таймфреймах  от м15 до м1 одинаково...

**Comment by icesoye** [comment]
http://prntscr.com/bqjcnc

**Comment by sbprov2** [comment]
Это разные аккумуляции, в одной точке. Алгоритм работает правильно. Это не ошибка.
