### ISSUE TITLE
Max Volume в баре (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#235]
Ребят, можно ли фильтр Max Volume Filter вместо числового значения просто поставить галочку и переименовать Max Volume Filter - Max Volume, отображать максимальный обьем кажого бара или нет? Это удобно - всегда можно отключить/включить, не всем нужен максимальный обьем, а постоянно ставить фильтр выше "среднего значения по палате" - ну это же геммор.
http://prntscr.com/br074o
Это поможет по нескольким причинам
1. Удобство включения/выключения
2. Можно включать/выключать не только на кластерном графике, но и на свечном (где то тут был тикет прикрутить на свечи макс обьем в свече)

Соотвественно переименовать, потому что фактически первого фильтра обьемов то и не было - фильтровался один максимальный кластер в кластере.

Отображение цветов
Second Volume - First Volume
Third Volume - Second Volume

Сами фильтры
Second Volume Filter - First Volume Filter
Third Volume Filter - Second Volume Filter

Ну и просто до кучи - 
Хотелось бы видеть опцию выбора цвета для Background в боковом и нижнем окнах индикаторов.
http://prntscr.com/br0xta

**Comment by Igor731** [comment]
Да, постоянно приходится его таким же, как Second Vol ставить. Проще просто галочку.

**Comment by sbprov2** [comment]
> Это удобно - всегда можно отключить/включить, не всем нужен максимальный обьем, а постоянно ставить фильтр выше "среднего значения по палате" - ну это же геммор.
Вы можете поставить 0, и у вас будут отображаться все объемы, или запредельно большое значение, чтобы ничего не отображалось. Не понимаю, в чем проблема ввести цифру и сохранить профиль или workspace.

> фильтровался один максимальный кластер в кластере.
Поэтому он и называется Max Volume Filter

> Хотелось бы видеть опцию выбора цвета для Background в боковом и нижнем окнах индикаторов.
Это сделаем.
