### ISSUE TITLE
Cloud alg

### ISSUE THREAD

**Issue by marrkusha** [sbprov2/SBProV2#239]
Привет всем спасибо разработчикам - все работает  и хотелось бы добавить  в клауд алгоритм фильтр  цепочек к примеру на стык интервалов например 5, 15 мин или стык часа -как то так.  То есть чтоб можно было фильтровать последовательности в последние минуты интервалов .  Так же можно добавить рисование  линий  произвольных например наклонных по  тренду  и добавить vwap индикатор ну и по аналогии с первой версией Dayly  volume profile очень нужная штука . Заранее спасибо .

**Comment by sbprov2** [comment]
Задачи нужно публиковать отдельно, а не в одном тикете 2000 задач.

**Comment by marrkusha** [comment]
спасибо что обратили внимание исправлюсь -тогда выложите правила подачи задач пожалуйста. Итак-задача  1. хотелось бы добавить в клауд алгоритм фильтр цепочек к примеру на стык интервалов например 5, 15 мин или стык часа -как то так. То есть чтоб можно было фильтровать последовательности в последние минуты интервалов
