### ISSUE TITLE
сохранение и запуск рабочих окон

### ISSUE THREAD

**Issue by marrkusha** [sbprov2/SBProV2#242]
Проблема при нажатии каких либо изменений aply начинает грузиться вноыь весь график -особо долго это происходит на росс рынке

**Comment by icesoye** [comment]
Это зависит от обьема котировок - больше тиковой истории грузится - медленее. Попробуйте s&p 500, самый ликвид - он вообще еле загружается.

**Comment by sbprov2** [comment]
Если Cloud - то конечно будет долго, это тиковые данные.
Плюс еще зависит от вашего интернета, у нас на 1 гигабит тики грузят отлично, а кеш вообще летает. Если вы сидите на медленном интернете, то это скорее проблема не платформы.

**Comment by marrkusha** [comment]
провайдер предоставляет максимум 100 мегабит а пропускная способность и того меньше

**Comment by marrkusha** [comment]
CL 220 днейзагружается порядка 10 секунд  евра 500 дней где то минуту но вот российский рынок грузится дольше раза в 3 интервал 200 дней.
