### ISSUE TITLE
Необходимые улучшения интерфейса (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#254]
Это только пожелания и как варианты реализации задач, как оно будет решать уже вам.
Честно просмотрел все тикеты, нашел только этот - https://github.com/sbprov2/SBProV2/issues/95

1. Перемещение графика в начало чарта, ведь перемещение в его конец уже есть. При анализе длинного временного периода очень нужная функция.
http://prntscr.com/bsnaee

2. Перемещение активной вкладки, чтобы не перетаскивать мышкой.
http://prntscr.com/bsnam7

**Comment by felukas68** [comment]
Абсолютно поддерживаю

**Comment by kichkin38** [comment]
+++++++++++++++

**Comment by net02worm** [comment]
++++++++++++

**Comment by RichAndHappy** [comment]
+
