### ISSUE TITLE
Нет доступа к sbpro2 -login error  

### ISSUE THREAD

**Issue by Hellenk** [sbprov2/SBProV2#261]
Не открывается программа -....    (hellkru@gmail.com)
Со свежим паролем тоже
Пожелания 
1) айсберг
1 )т.ф. 2часа
2)Работа с увеличенным экраном

**Comment by oleg1ci** [comment]
вчера письма рассылали про эту проблему, сказали что скачать последнюю версию надо, и после обновления "login error" проходит.

**Comment by Hellenk** [comment]
Как раз проблема появилась после скачивания новой версии

**Comment by Hellenk** [comment]
Какой выход ? 


Regards!

**Comment by Hellenk** [comment]
Дайте пож . эту версию (ссылкой)

Regards!

**Comment by oleg1ci** [comment]
мне такая ссылка в письме пришла: https://drive.google.com/open?id=0B1xBffySxO6sakRROTlMUmd1LTg

**Comment by Hellenk** [comment]
Не пашет

Regards!

**Comment by sbprov2** [comment]
@Hellenk  Обратитесь в тех. поддержку по Skype

**Comment by sbprov2** [comment]
@Hellenk отправили вам новый аккаунт. Скорее всего вы регистрировали trial до этого, чего делать было не нужно, так как у вас есть платный аккаунт. Все триал мы удалили, и соответственно, вашего email не оказалось в базе. Тикет закрыт.
