### ISSUE TITLE
Ошибка сохранения Workspace (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#279]
Ошибка критическая, так что будьте аккуратны. Повторять не рекомендую.

1. У нас есть какие то Workspace сохраненные (неважно какие)
2. Сохраняем Workspace c пустым именем (не вводим ничего вообще)
3. Вуаля - все ваши сохраненные рабочие столы удалены, а вместо них есть один с именем Chart.1 и если загрузить его - программа вылетит, то же самое в окне логина - при установленном Chart.1 рабочем столе программа просто не запустится.

На профилях тоже стоит это проверить, мне пока хватило удаления рабочих столов.

**Comment by AleksKov12** [comment]
В бесплатной версии тоже такой глюк был.

20 июля 2016 г., 7:04 пользователь icesoye <notifications@github.com>
написал:
