### ISSUE TITLE
воркспейс

### ISSUE THREAD

**Issue by megatronsam** [sbprov2/SBProV2#281]
привет,
такое пожелание, поправить принцип сохранения и загрузки workspace,
при загрузке платформы и указания workspace, загружает с момента сохранения workspace по текущий день, а это получается очень много, и каждый день этот период увеличивается на 1 день. может  сохранять только сами вкладки инструментов и настройки чарта, а период просто выставлялся с (-3 от текущего дня) по (текущий день)
Или если я неверно сохраняю, то поправьте 
спасибо
http://prntscr.com/bvk25b

**Comment by ershner** [comment]
Мне тоже это не очень нравится, особенно на медленном интернете очень долго прогружается

**Comment by kichkin38** [comment]
да да,+++++++++++++

**Comment by oleg1ci** [comment]
+++ лучше указывать количество загружаемых дней из истории, чем начальную дату

**Comment by RichAndHappy** [comment]
+

**Comment by test-777** [comment]
Поддерживаю, ато каждый раз переключать приходиться.
