### ISSUE TITLE
проблема с подключением к рынку РФ....

### ISSUE THREAD

**Issue by Fen8fen** [sbprov2/SBProV2#286]
Здравствуйте.
Отпишитесь пожалуйста, у кого проблемы с подключение к фьючерсам Сбербанка и Газпрома....
Отсутствуют котировки.
Техподдержка упорно молчит....

**Comment by Ekrem8998** [comment]
да, кажется у всех, вчера на открытии тоже были проблемы

**Comment by Fen8fen** [comment]
Вы кто техподдержка?


>Пятница, 22 июля 2016, 16:02 +08:00 от Ekrem8998 <notifications@github.com>:
>
>да, кажется у всех, вчера на открытии тоже были проблемы
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением:
Alexandr Buglak

**Comment by Ekrem8998** [comment]
нет) прошу  прощения, нажал случайно кнопку "closed"
