### ISSUE TITLE
Ценовые линии

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#288]
Ценовые линиии у вас сейчас сжимаются и растягиваются вместе с графиком. Это совершенно не нужно. Их толщина должна быть постоянной и задаваемой. Как и цвет. А также должна быть возможность их перемещать. Перекрестие тоже не нужно растягивать и сжимать.

**Comment by icesoye** [comment]
>Их толщина должна быть постоянной и задаваемой.  

ну это же неосуществимо, цена сжимается и сжимается линия на цене которой она стоит, если я, допустим, поставил линию на цену 45, сжал график и линия стала на цены 44-46, зачем такое нужно то??

**Comment by sbprov2** [comment]
> Их толщина должна быть постоянной и задаваемой

Сегодня 1-е апреля? @icesoye вам объяснил, почему это невозможно.
