### ISSUE TITLE
про горизонтальные линии (oleg1ci@yandex.ru)

### ISSUE THREAD

**Issue by oleg1ci** [sbprov2/SBProV2#293]
Горизонтальные линии и "линии разделения периодов" надо рисовать под свечами, а то теней свечи невидно..
![2016-07-26_224827](https://cloud.githubusercontent.com/assets/18282738/17145283/cd4a966a-5383-11e6-8073-50d39150ba39.png)

**Comment by icesoye** [comment]
Линии вроде вертикальные, не?

**Comment by oleg1ci** [comment]
действительно вертикальные :)

**Comment by Ekrem8998** [comment]
да есть такая проблема
