### ISSUE TITLE
Инструмент 6J, а его закладка Si 1 hour

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#295]
Происходит при загрузке сохраненного воркспейс.
![sb-pro-v2 21](https://cloud.githubusercontent.com/assets/19690193/17202106/c862b89a-549f-11e6-905e-1c5b62a61c02.jpg)

**Comment by oleg1ci** [comment]
тоже видел такой глюк, когда нажимал apply и сразу же нажимал на какую-нибудь вкладку с другим инструментом

**Comment by TruckersO** [comment]
+1

**Comment by icesoye** [comment]
вот тут подробно описывал - https://github.com/sbprov2/SBProV2/issues/253 , но есть еще пара глюков с именами. Вы  скорей всего обновляли график Si И щелкнули на 6J - и глюкнуло.

**Comment by sbprov2** [comment]
Данная проблема учтена, будет исправлено в обновлении.
