### ISSUE TITLE
По какой причине количество вкладок ограничено 10?

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#297]

**Comment by icesoye** [comment]
Так есть же возможность сделать новый чарт, и еще 10 вкладок будет.

**Comment by Igor731** [comment]
Так и делаю, но это менее удобно.

**Comment by icesoye** [comment]
>Так и делаю, но мне это менее удобно.

В большинстве других программ, которые так любят приводить тут в пример, вкладок нет вообще :)

**Comment by Igor731** [comment]
В Маркетдельте есть. Волфиксом и Атасом не пользовался.

**Comment by Igor731** [comment]
Если причина веская, то конечно. Если же нет, то просьба не ограничивать.

**Comment by yamaha72** [comment]
Сколько нужно сделать ?
