### ISSUE TITLE
+ обсуждение тикера!!! (zhivits@gmail.com) 

### ISSUE THREAD

**Issue by zhivik007** [sbprov2/SBProV2#298]
Уважаемые соучредители платформы!
...Высказывайтесь за предложение описанное в тикере:
+про профиль ClusterProfile   #278 ....
Ваше мнение очень существенно для разработчиков!!!

**Comment by sbprov2** [comment]
Не тикер, и тикет.
Пожалуйста, не дублируйте информацию, если уже тикет создан - зачем создавать еще один и призывом обсудить другой тикет. Ну сколько же можно вас просить...
