### ISSUE TITLE
Режим Бид\Аск Ладдер

### ISSUE THREAD

**Issue by Fen8fen** [sbprov2/SBProV2#302]
Здравствуйте. Добавьте пожалуйста режим просмотра "бид.аск ладдер" .

![bid_ask_ladder](https://cloud.githubusercontent.com/assets/20509322/17269329/e6545262-5677-11e6-9e60-413b0640038d.jpg)

**Comment by Fen8fen** [comment]
![bid_ask_ladder](https://cloud.githubusercontent.com/assets/20509322/17269525/68c32340-567d-11e6-8833-89c3554a20e2.jpg)

**Comment by kichkin38** [comment]
++++++++++++++

**Comment by sbprov2** [comment]
Что это и чем не устраивает режим bid-ask?

**Comment by kichkin38** [comment]
да да,сразу и не въехал,полностью согласен.

**Comment by Fen8fen** [comment]
Да это тот же бид аск но здесь визуально проще отследить объемы. Они подсвечиваются по фильтру. по дельте.

**Comment by sbprov2** [comment]
> Они подсвечиваются по фильтру. по дельте.

Поставьте фильтр по дельте, и все будет так же видно.
Вопрос исчерпан?
