### ISSUE TITLE
ошибка в клаудсе

### ISSUE THREAD

**Issue by marrkusha** [sbprov2/SBProV2#311]
![default](https://cloud.githubusercontent.com/assets/20208124/17399836/ef1d1cdc-5a5d-11e6-84ef-aa715f38ef1e.png)

почему   не показывает направления  бид или аск ?  белый бордер хотя клауд появился.

**Comment by sbprov2** [comment]
Публикуйте сразу скриншот настроек, чтобы можно было проверить. Спасибо.
