### ISSUE TITLE
Технические работы с 04.08 - 10.08 (support@sb-professional.com)

### ISSUE THREAD

**Issue by sbprov2** [sbprov2/SBProV2#313]
На данный момент мы работаем над улучшением серверной части (передача данных), и для этой задачи нам **необходимо** периодически прерывать поток данных, чтобы выявить причины существующих ошибок. Сделать это можно только на реальном сервере с потоком клиентов.

Надеемся что фикс багов пройдет быстро. 
Заранее просим прощения за неудобства.

**Comment by ershner** [comment]
Как временное решение пока технические работы
https://www.youtube.com/watch?v=j-OuE9_4Kj8&list=WL&index=139 Платформа сме futures. Есть Time&Sales и объемы в реальном времени. Демка на 2 недели.

**Comment by icesoye** [comment]
Лучше уж взять демо Ниндзи - те же 2 недели, и прикрутить это туда все, нет?
