### ISSUE TITLE
От куда бары в воскресенье? (oleg1ci@yandex.ru)

### ISSUE THREAD

**Issue by oleg1ci** [sbprov2/SBProV2#315]
Интересно от куда бары на графике в ВОСКРЕСЕНЬЕ на графике валютных фьючерсов? зашел на биржу Чикагскую на сайте [http://www.cmegroup.com/](url) там на фьючерсе евро 6Е нету воскресенья. Вот скиншоты, первый SBPro, второй с фьючерса cmegroup.com.
![2016-08-05_182000](https://cloud.githubusercontent.com/assets/18282738/17437180/6f421fa0-5b46-11e6-87db-28c83cc6a5f3.png)
![2016-08-05_182605](https://cloud.githubusercontent.com/assets/18282738/17437182/72393acc-5b46-11e6-88b4-4611ec0a2ab5.png)

**Comment by sbprov2** [comment]
Ну как же - торги начинаются в воскресенье, в 17.00 по Чикаго.

**Comment by sbprov2** [comment]
Так как в платформе считаются дни по Чикаго - есть отдельный день за ВС.

**Comment by oleg1ci** [comment]
> Ну как же - торги начинаются в воскресенье, в 17.00 по Чикаго.
блин не знал что по выходным работают :)
