### ISSUE TITLE
Формат времени для графиков выше секундных (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#317]
Если есть возможность, то хотелось бы видеть изменение/привязку формата временной шкалы на дневных (да и везде где секунды не используются) графиках
с
**День.Месяц Час.Минута.Секунда** 
на 
**День.Месяц.Год Час.Минута**
а то сейчас везде показывает время - День.Месяц 00.00.00 (на дневных, к примеру) и не понятно какой год вообще, и зачем секунды.
http://prntscr.com/c2kxcs

А ниже минутного чтобы исчезали годы и появлялись секунды. Имхо так было бы правильней и удобней для анализа. (а в будущем, если появится copy-paste линий, так вообще не заменимая функция)

**Comment by sbprov2** [comment]
Принято
