### ISSUE TITLE
предложение реализовать DTC protocol

### ISSUE THREAD

**Issue by u1ysses** [sbprov2/SBProV2#318]
приветствую,
в качестве предложения, как вариант data feed, можно было рассмотреть возможность получения данных по DTC protocol от Sierra Chart - как например сделали  разработчики HiddenFluxForce. (http://www.sierrachart.com/index.php?page=doc/DTCProtocol.php) Элегантное решение, если и не решающее в целом проблему качественного и устойчивого дата фида, но по крайней мере, иметь возможность такого подключения, среди прочих вариантов было бы совсем не лишним. Насколько я понимаю, у вас в перспективе все ровно маячит вопрос о наличии подключений к разному дата фид (CQG, Rithmic etc). Отсутствие DTC приведет к необходимости оплачивать за дополнительную точку получения данных - то есть один получатель - платформа с execution,  а второй - ваша платформа (в будущем), а наличие возможности получения данных по DTC отчасти помогло бы решить проблему.

**Comment by sbprov2** [comment]
Это в принципе не актуально, потому что с 15.08 будет подключение к Ninjatrader - а там вы уже можете выбрать любой провайдер, который доступен в ninjatrader. Их так не мало.

**Comment by u1ysses** [comment]
Я не пользуюсь Ниндзя Трейдер, мой брокер АМП не предлагает НТ, как таковую. Сводя возможность подключения только к НТ вы тем самым сужаете круг пользователей, далеко не все пользуются НТ, и тем более этим брокером. В одном из обсуждении по скайп одним из ваших разработчиков была сказано, что вы планируете возможность подключения к различному дата фид, теперь как оказалось все это свелось к подключению к далеко не самой лучшей платформе. Пичалька!

**Comment by sbprov2** [comment]
Подключение ко всем провайдерам это весьма серьезный кусок работы. 
Пока первое решение - это Ninjatrader и Quik. 
Естесственно что постепенно будем добавлять варианты подключений. Не все сразу.
Технически, если у вас есть логин и пароль от любого провайдера из списка в NT - вы можете подключиться к фиду, и он будет транслироваться в SB. Вопрос удобства пока за кадром.

**Comment by u1ysses** [comment]
как уже говорил, мой дата фид поставщик потребует с меня дополнительной оплаты за поток данных на дополнительную платформу. Это не вопрос удобства, а оптимизации костов. Не знаю как вы решаете вопрос получения данных через ниндзя, но если бы вы изначально сказали что предпочтение разработчиков будет отдано НТ и квик, я бы подумал, прежде чем вкладываться. Останется ли ваш собственный "бесплатный" дата фид в качестве опции, или с переходом на подключение к НТ и квику мне, человек не пользующимся и не собирающимся пользоваться НТ можно будет закинуть платформу на полку?

**Comment by sbprov2** [comment]
@u1ysses по поводу фида напишите нам в skype, вам объяснят все ньюансы.
