### ISSUE TITLE
Толщина линий должна быть постоянной и настраиваемой. Хотя бы, как в МТ4.

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#319]
Не нормально ни так:
![sb-pro-v2 28](https://cloud.githubusercontent.com/assets/19690193/17465865/8f941abc-5d01-11e6-931a-25e65aed247f.jpg)
Ни так:
![sb-pro-v2 29](https://cloud.githubusercontent.com/assets/19690193/17465867/99dbfda0-5d01-11e6-8279-9ff6d5c8767f.jpg)
Уверен, что толщина не должна растягиваться и сужаться вместе с графиком по шкале цены. Если при  сжатии графика линия начинает занимать дополнительные пипсы - это нормально. При сужении графика пипсы и даже пункты тоже сливаются. И шаг цены на оси цен увеличивается. Так и должно быть. Линия должна быть одинаково видна, как при растяжении, так и при сужении графика, а не превращаться то в толстую, то в мало-видимую.
P.S. Про 1 апреля можно еще раз? А то в прошлый не все шутку поняли.

**Comment by sbprov2** [comment]
Я сразу отклоняю Вашу идею, даже если ее тут все поддержат.
Почему: 
1. Потому что на наше взгляд это сильно все испортит визуально. 
2. Вы не привели никаких толковых обоснований, только "что толщина не должна растягиваться", или "это нормально", "Так и должно быть", "Линия должна быть одинаково видна".
Все очень субьективно, и это ваше личное мнение.
3. Придется переписывать некоторую часть движка графика, это долго и не нужно. 

> Линия должна быть одинаково видна, как при растяжении, так и при сужении графика, а не превращаться то в толстую, то в мало-видимую.

Я считаю что не должна. Мне так не нравится. Наоборот, старались сделать читабельные линии. Почему линия должна быть тонкой на кластере? Это же не удобно.

Отклонено, извините если Вам не нравятся линии.

**Comment by Igor731** [comment]
Re: [sbprov2/SBProV2] Толщина линий должна быть постоянной и настраиваемой. Хотя бы, как в МТ4. (#319)


Здравствуйте, sbprov2.


  Но хотя бы сделайте, чтобы в сжатом виде их нормально видно было.


Вы писали 8 августа 2016 г., 15:00:20:





Я сразу отклоняю Вашу идею, даже если ее тут все поддержат.
Почему: 
1. Потому что на наше взгляд это сильно все испортит визуально. 
2. Вы не привели никаких толковых обоснований, только "что толщина не должна растягиваться", или "это нормально", "Так и должно быть", "Линия должна быть одинаково видна".
Все очень субьективно, и это ваше личное мнение.
3. Придется переписывать некоторую часть движка графика, это долго и не нужно. 
Линия должна быть одинаково видна, как при растяжении, так и при сужении графика, а не превращаться то в толстую, то в мало-видимую.
Я считаю что не должна. Мне так не нравится. Наоборот, старались сделать читабельные линии. Почему линия должна быть тонкой на кластере? Это же не удобно.
Отклонено, извините если Вам не нравятся линии.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
С уважением,
 Ермаков                          mailto:ermak13@gmail.com
