### ISSUE TITLE
Закрывать диалог сохранения пространства/профиля, если успешно.

### ISSUE THREAD

**Issue by Igor731** [sbprov2/SBProV2#321]
Редко, когда нужно одно и то же пространство или профиль сохранять под разными именами. Поэтому каждый раз приходится двигать мышь и закрывать окно. Лучше его сразу же закрывать автоматом при успешном сохранении.

**Comment by sbprov2** [comment]
> Поэтому каждый раз приходится двигать мышь и закрывать окно.

А если нужно пользователю сохранить workspace, но не закрывать платформу (или окно)?
Предложение не годится.
