### ISSUE TITLE
у меня завис сб-2  (eldar-han92@mail.ru)

### ISSUE THREAD

**Issue by Eldar922** [sbprov2/SBProV2#322]
![screenshot_1](https://cloud.githubusercontent.com/assets/19773999/17477772/ccf90156-5d6f-11e6-872a-c7e934e380cb.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/19773999/17477775/d09e34f2-5d6f-11e6-8e5d-885f1d06303a.png)

**Comment by Eldar922** [comment]
пару раз так было уже

**Comment by kichkin38** [comment]
Писали же до 10 числа возможны баги
