### ISSUE TITLE
Вопрос к разработчикам (ice.soye@gmail.com)

### ISSUE THREAD

**Issue by icesoye** [sbprov2/SBProV2#324]
Так как эта тема много раз поднималась тут, но в свете новых возможностей (коннекторы к терминалам) еще раз задам - будет ли транслироваться Level 2 через коннектор и, если да, будут ли использоваться его возможности? (например как в BookMap)

зы. как ответите, можно выпиливать.

**Comment by sbprov2** [comment]
Добрый день. L2 пока в планах нет. Однако получать данные можно через терминалы, соответственно, осенью можно будет заняться и L2.
