### ISSUE TITLE
Открытый интерес

### ISSUE THREAD

**Issue by tessals** [sbprov2/SBProV2#326]
Возможно ли реализовать с платформе индикатор открытого интереса для российского рынка?

**Comment by marrkusha** [comment]
открытый интерес биржа транслирует открыто стало быть если захотят разрабы то ОИ мы увидим на экранах.

**Comment by RichAndHappy** [comment]
#268 #56

**Comment by tessals** [comment]
Просмотрел архив, прочитал ответы, ждем-с вместе со всеми ОИ, я его использую в торговле)
