### ISSUE TITLE
Загрузка данных при обновлении параметров Cloud (aleksej63@hotmail.com)

### ISSUE THREAD

**Issue by alferro** [sbprov2/SBProV2#332]
Уважаемые разработчики, спасибо за глобальное обновление, данные действительно стали загружаться быстрее, с мобильного интернета вроде бы тоже грузит, но и тут не обошлось без ложки дегтя...
При изменении параметров Cloud, будь то числовые значения или включение/отключение параметров, при нажатии кнопки apply данные начинают заново подгружаться, причем, судя по скорости, грузятся явно не из кеша. Загрузка 150 дней заняла 3 минуты 34 сек. Причем загрузка и обновление экрана происходит независимо от того, были ли какие изменения в настройках или нет. Тупо нажимаем аплай и жлем 4 минуты на поугодовую историю, ТФ 1ч.

**Comment by sbprov2** [comment]
Cloud работает только с тиками - поэтому медлено.

**Comment by alferro** [comment]
т.е. закешировать данные нет возможности? Что бы в момент изменения настроек он подгружал данные из кеша?

**Comment by sbprov2** [comment]
Конечно нет. Изучите алгоритм и поймете, что закешировать его невозможно.

**Comment by alferro** [comment]
Спасибо за оперативный ответ
