### ISSUE TITLE
Горизонтальный объем не реагирует на настройки параметра MaxVolumeFilterColor (aleksej63@hotmail.com)

### ISSUE THREAD

**Issue by alferro** [sbprov2/SBProV2#335]
При настройке цвета максимальных объемов ничего не происходит. Объемы окрашиваются только при изменении настроек вторичного и третичного параметра.
![default](https://cloud.githubusercontent.com/assets/18305082/17679488/50e3ac58-6344-11e6-9c4b-07525ac304b4.PNG)

**Comment by sbprov2** [comment]
Вы не понимаете как рабоает этот фильтр. Он подсвечивает ТОЛЬКО максимальный объем, а не все объемы свыше 50000. Для этого есть параметр Second и Third

**Comment by sbprov2** [comment]
Тикет закрыт, так как это НЕ ошибка
