### ISSUE TITLE
+ исторические данные (zhivits@gmail.com)

### ISSUE THREAD

**Issue by zhivik007** [sbprov2/SBProV2#336]
...данные глубже января 2016 ни с какого поставщика не загружаются!!!
и снова формат времени на шкале кур
![16 08](https://cloud.githubusercontent.com/assets/19731162/17681017/db6d4e86-634b-11e6-9815-357cf120d6f8.png)
сора...

**Comment by RoketAnny** [comment]
++

**Comment by sbprov2** [comment]
Прежде чем создавать такие тикеты, хотя бы посмотрели бы список контрактов для 6E. Первый контракт 03-16. Дальше данных НЕТ! Зачем же вы грузит 2014-й? Тикет закрыт.
