### ISSUE TITLE
+ (+7 и -7) (Т) (-1и+1) данные (zhivits@gmail.com)

### ISSUE THREAD

**Issue by zhivik007** [sbprov2/SBProV2#337]
![16 083](https://cloud.githubusercontent.com/assets/19731162/17681645/a1035228-634f-11e6-963a-af458189e479.png)
![16 084](https://cloud.githubusercontent.com/assets/19731162/17681648/a59caaf0-634f-11e6-8724-631f1b0ed593.png)

![16 082](https://cloud.githubusercontent.com/assets/19731162/17681428/55a03c52-634e-11e6-93a2-fee91cc3025d.png)

**Comment by sbprov2** [comment]
Вы вероятно не понимаете как работает эта панель. С чего вы взяли что должна грузится неделя от T? -7 просто сдвигает начальную и конечную дату на 7 дней назад. -1 работает точно так же.

Хватит публиковать несуществующие проблемы, сначала возьмите и разберитесь, или хотябы спросите в skype тех. поддержки как это работает.
