### ISSUE TITLE
Не могу зайти в терминал!!!

### ISSUE THREAD

**Issue by Roman1970roman** [sbprov2/SBProV2#338]
В чем причина? Логин и пароль не изменял и они правильные, но платформа выдает ошибку входа.   
http://joxi.ru/J2b1bRbc495B8m

**Comment by Zench7** [comment]
Добрый день. Такая же проблема с терминалом. Вчера 15.08 входил свободно и работало все стабильно. При коннекте выводит туже ошибку.
![3](https://cloud.githubusercontent.com/assets/19830759/17690975/7e5843d0-63ab-11e6-9e98-94d446c8a835.jpg)

**Comment by akonkov** [comment]
Скачайте новый дистрибутив с сайта http://www.sb-professional.com/download
 и переустановите платформу....

**Comment by Zench7** [comment]
Спасибо! Все работает.
