### ISSUE TITLE
рейтинг клаудов

### ISSUE THREAD

**Issue by megatronsam** [sbprov2/SBProV2#340]
Привет,
объясните пожалуйста, почему клауд с объемом 397 контрактов намного меньше клауда с объемом 218
настройка рэйтинг не приносит никаких результатов
в старой версии чем больше объем клаудса тем больше он по размеру
![screenshot_1](https://cloud.githubusercontent.com/assets/20474003/17698116/dbc1c008-63c1-11e6-827c-4c8bc65a17c3.png)

**Comment by sbprov2** [comment]
Потому что у вас стоит bid-ask. Это значит что рейтинг строится не по объему, а по проценту перевеса.

**Comment by megatronsam** [comment]
вот оно что, спасибо за разъяснения
